import Link from 'next/link';
import { ArrowDown, ArrowUpRight, ArrowRight, Download } from 'lucide-react';
import { featuredProjects, site } from '@/lib/content';
import { ProjectVisual } from '@/components/portfolio/project-visual';
export default function Home(){return <main id="main"><section className="hero" aria-labelledby="hero-title"><picture className="hero-art"><source media="(max-width:700px)" srcSet="/media/observatory-mobile.webp"/><img src="/media/observatory.webp" alt="" width={1672} height={941} fetchPriority="high"/></picture><div className="hero-shade"/><div className="hero-content"><div className="eyebrow hero-eyebrow"><span className="signal-cross">✳</span> AI · HARDWARE · HUMAN CURIOSITY</div><h1 id="hero-title"><span>Ideas, made</span><span><em>tangible.</em></span></h1><p>{site.person.intro}</p><Link href="#work" className="pill-button">Explore my work <ArrowDown size={17}/></Link></div><div className="hero-coordinate">THE BUILDER’S<br/>OBSERVATORY — 01</div><div className="hero-bottom"><span>BASED IN NAGPUR, INDIA<br/><b>BUILDING BEYOND BOUNDARIES</b></span><span className="hero-center">BS–MS · IIT PATNA</span><a href="#work">SCROLL TO DISCOVER <ArrowDown size={14}/></a></div></section>
<div className="discipline-strip" aria-label="Focus areas"><span>AI SYSTEMS</span><i>✳</i><span>CONNECTED HARDWARE</span><i>✳</i><span>WEB EXPERIENCES</span><i>✳</i><span>APPLIED RESEARCH</span><i>✳</i></div>
<section id="work" className="work-section section-pad"><div className="section-heading"><div><div className="eyebrow"><span className="section-number">01</span> SELECTED EXPLORATIONS</div><h2>Built with intent.<br/><em>Made to work.</em></h2></div><p>A selection of systems, experiments,<br/>and ideas brought into the real world.</p></div><div className="work-layout"><aside className="work-index"><span className="eyebrow">THE COLLECTION</span>{featuredProjects.map((p,i)=><a key={p.slug} href={`#project-${p.slug}`} className="work-index-link"><span>0{i+1}</span>{p.title}<ArrowUpRight size={14}/></a>)}<Link href="/projects" className="text-link">All projects <ArrowRight size={17}/></Link><p>Software. Hardware.<br/>Different tools.<br/>The same curiosity.</p></aside><div className="work-list">{featuredProjects.map((p,i)=><article className="featured-project" id={`project-${p.slug}`} key={p.slug}><Link href={`/projects/${p.slug}`} className="project-media-link" aria-label={`Read ${p.title} case study`}><ProjectVisual project={p}/><span className="case-study-chip">Explore project <ArrowUpRight size={16}/></span></Link><div className="project-meta"><span>{p.category.toUpperCase()}</span><span>{p.year}</span></div><div className="project-title-line"><h3><Link href={`/projects/${p.slug}`}>{p.title}<span className="project-counter">0{i+1}</span></Link></h3><Link href={`/projects/${p.slug}`} className="round-link" aria-label={`Read ${p.title}`}><ArrowUpRight/></Link></div><p className="project-summary">{p.summary}</p><div className="tags">{p.tags.slice(0,3).map(t=><span key={t}>{t}</span>)}</div></article>)}</div></div></section>
<section className="about-section section-pad" id="about"><div className="eyebrow"><span className="section-number">02</span> THE PERSON BEHIND THE PROJECTS</div><div className="about-layout"><h2>Curiosity is<br/>my <em>starting point.</em></h2><div><p className="about-lead">{site.person.bio}</p><p>Some days that means coordinating AI agents. Others, it means calibrating a sensor or asking a better research question. I like making the pieces work together.</p><Link href="/about" className="text-link">A little more about me <ArrowUpRight size={18}/></Link></div></div><div className="education-strip"><span>IIT PATNA</span><div>BS–MS · Computer Science & Data Analytics<small>2025 — 2030 (expected)</small></div><a href={site.person.resume} download>Résumé <Download size={16}/></a></div></section>
<section className="experience-section section-pad"><div className="section-heading"><div><div className="eyebrow"><span className="section-number">03</span> LEARNING BY DOING</div><h2>Work, and<br/><em>the work around it.</em></h2></div><Link href="/about#experience" className="text-link">Full experience <ArrowUpRight size={18}/></Link></div><div className="experience-list">{site.experience.map(e=><article key={e.title}><span className="experience-period">{e.period}</span><div><h3>{e.title}</h3><p>{e.organization}</p></div><p>{e.body}</p></article>)}</div></section>
<section className="recognition-section section-pad" id="recognition"><div className="section-heading"><div><div className="eyebrow"><span className="section-number">04</span> MOMENTS ALONG THE WAY</div><h2>Out in <em>the world.</em></h2></div><span className="eyebrow">2021 — 2026</span></div><div className="recognition-list">{site.recognition.map((r,i)=><article key={r.title}><span className="recognition-index">0{i+1}</span><div><h3>{r.title}</h3><p>{r.body}</p></div><span className="award-result">{r.result}</span><span className="award-date">{r.date}</span></article>)}</div></section></main>}
