'use client';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { Save, Plus, ArrowUp, ArrowDown, Trash2, Upload, Download, ArrowUpRight } from 'lucide-react';
import { Switch } from '@/components/ui/switch';
type Value=string|boolean|Value[]|{[key:string]:Value};
type Content={ [key:string]:Value };
const labels=(s:string)=>s.replace(/([A-Z])/g,' $1').replace(/\b\w/g,c=>c.toUpperCase());
function Field({value,onChange,name}:{value:Value;onChange:(v:Value)=>void;name:string}){if(typeof value==='boolean')return <label className="studio-toggle"><Switch checked={value} onCheckedChange={onChange}/>{labels(name)}</label>;if(typeof value==='string'&&name==='type')return <label className="studio-field"><span>Media type</span><select value={value} onChange={e=>onChange(e.target.value)}>{['image','video'].map(v=><option key={v}>{v}</option>)}</select></label>;if(typeof value==='string')return <label className="studio-field"><span>{labels(name)}</span>{['body','summary','bio','intro','problem','approach','outcome','limitations','next','story','transcript'].includes(name)?<textarea rows={4} value={value} onChange={e=>onChange(e.target.value)}/>:<input value={value} onChange={e=>onChange(e.target.value)}/>}</label>;if(Array.isArray(value))return <fieldset className="studio-array"><legend>{labels(name)}</legend>{value.map((v,i)=><div className="studio-array-row" key={i}><Field name={`${name} ${i+1}`} value={v} onChange={next=>onChange(value.map((x,j)=>j===i?next:x))}/><button disabled={name==='architecture'} className="icon-button" aria-label={`Remove ${name} ${i+1}`} onClick={()=>onChange(value.filter((_,j)=>j!==i))}><Trash2 size={15}/></button></div>)}<button disabled={name==='architecture'} className="studio-small" onClick={()=>onChange([...value,name==='decisions'?{title:'New decision',body:''}:name==='media'?{type:'image',src:'',alt:'',caption:'',poster:'',transcript:''}:''])}><Plus size={14}/> Add {name==='decisions'?'decision':'item'}</button></fieldset>;return <div className="studio-fields">{Object.entries(value).map(([k,v])=><Field key={k} name={k} value={v} onChange={next=>onChange({...value,[k]:next})}/>)}</div>}
export function ContentEditor(){const[data,setData]=useState<Content|null>(null);const[section,setSection]=useState('projects');const[index,setIndex]=useState(0);const[status,setStatus]=useState('Loading local editor…');const[dirty,setDirty]=useState(false);const[busy,setBusy]=useState(false);const[unavailable,setUnavailable]=useState(false);
useEffect(()=>{fetch('/_studio/content').then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{setData(d as Content);setStatus('Ready. Changes save to this computer.')}).catch(()=>{setUnavailable(true);setStatus('The editor runs with your local development server.')})},[]);
useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue=''}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn)},[dirty]);
function change(next:Content){setData(next);setDirty(true);setStatus('Unsaved changes')}
async function save(){if(!data)return;setBusy(true);setStatus('Saving…');try{const r=await fetch('/_studio/content',{method:'POST',headers:{'Content-Type':'application/json','X-Portfolio-Studio':'local'},body:JSON.stringify(data)});const result=await r.json() as {error?:string;path:string};if(!r.ok)throw Error(result.error);setDirty(false);setStatus('Saved locally. Open the portfolio to preview; publish again to update the hosted site.')}catch(e){setStatus(e instanceof Error?e.message:'Save failed. Your changes are still in the editor.')}finally{setBusy(false)}}
function download(){if(!data)return;const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='portfolio-content-backup.json';a.click();URL.revokeObjectURL(url)}
async function upload(file:File){if(file.size>64*1024*1024){setStatus('Choose a file smaller than 64 MB.');return}setBusy(true);try{const r=await fetch('/_studio/upload',{method:'POST',headers:{'Content-Type':file.type,'X-Portfolio-Studio':'local'},body:file});const result=await r.json() as {error?:string;path:string};if(!r.ok)throw Error(result.error);if(data&&section==='events'){const list=data.events as Content[];change({...data,events:list.map((event,i)=>i===index?{...event,media:[...(event.media as Value[]),{type:file.type.startsWith('video/')?'video':'image',src:result.path,alt:file.name.replace(/\.[^.]+$/,'').replace(/[-_]/g,' '),caption:'',poster:'',transcript:''}]}:event)});setStatus('Media uploaded. Edit its description, caption and optional transcript, then save.')}if(data&&section==='projects'){const list=data.projects as Content[];change({...data,projects:list.map((p,i)=>i===index?{...p,image:result.path}:p)});setStatus('Image uploaded. Add descriptive Image Alt text, then save.')}}catch(e){setStatus(e instanceof Error?e.message:'Upload failed')}finally{setBusy(false)}}
if(unavailable)return <div className="studio-unavailable"><h2>Your publishing workbench.</h2><p>Open this page on your computer while the portfolio development server is running. The editor saves projects, notes, and profile updates into your website files.</p><p>The hosted portfolio has no public editing endpoint. After saving, ask Codex to publish your changes.</p><Link href="/projects" className="pill-button">Back to the portfolio <ArrowUpRight size={16}/></Link></div>;
if(!data)return <p role="status">{status}</p>;const array=Array.isArray(data[section]);const list=array?data[section] as Content[]:[];const current=array?list[index]:data[section];
function add(){if(!data)return;let item:Content;if(section==='projects'){item={category:'Web experiences',year:new Date().getFullYear().toString(),status:'In progress',visual:'project',role:'',team:'',slug:`new-project-${Date.now()}`,title:'Untitled project',subtitle:'',published:false,featured:false,repo:'',demo:'',image:'',imageAlt:'',summary:'',recognition:'',upstream:'',problem:'',approach:'',outcome:'',limitations:'',next:'',decisions:[],tags:[],architecture:['Input','Process','Review','Output']}}else if(section==='events')item={slug:`new-event-${Date.now()}`,title:'Untitled event',category:'Participation',result:'Participant',date:'',location:'',summary:'',story:'',projectSlug:'',source:'',published:false,media:[]};else if(section==='writing')item={slug:`new-note-${Date.now()}`,title:'Untitled note',date:new Date().toISOString().slice(0,10),summary:'',body:'',published:false};else if(section==='experience')item={title:'New experience',organization:'',period:'',body:''};else if(section==='recognition')item={title:'New recognition',result:'',date:'',body:''};else item={title:'New skill group',items:[]};change({...data,[section]:[...list,item]});setIndex(list.length)}
function move(direction:number){if(!data)return;const target=index+direction;if(target<0||target>=list.length)return;const updated=[...list];[updated[index],updated[target]]=[updated[target],updated[index]];change({...data,[section]:updated});setIndex(target)}
return <div className="studio"><div className="studio-toolbar"><div><span className="eyebrow">LOCAL CONTENT STUDIO</span><p role="status">{status}</p></div><button className="studio-small" onClick={download}><Download size={16}/> Backup</button><button className="pill-button" onClick={save} disabled={busy||!dirty}><Save size={16}/> Save changes</button></div><div className="studio-layout"><aside><nav aria-label="Content sections">{Object.keys(data).map(key=><button key={key} aria-pressed={key===section} onClick={()=>{setSection(key);setIndex(0)}}>{labels(key)}</button>)}</nav>{array&&<div className="studio-records">{list.map((item,i)=><button key={i} aria-pressed={i===index} onClick={()=>setIndex(i)}>{String(item.title||`Item ${i+1}`)}{item.published===false&&<small>Draft</small>}</button>)}<button className="studio-small" onClick={add}><Plus size={16}/> Add {section==='writing'?'note':section==='projects'?'project':'entry'}</button></div>}</aside><section className="studio-form">{current?<><div className="studio-record-toolbar"><h2>{array?String((current as Content).title):labels(section)}</h2>{array&&<><button className="icon-button" disabled={!index} onClick={()=>move(-1)} aria-label="Move entry up"><ArrowUp size={16}/></button><button className="icon-button" disabled={index===list.length-1} onClick={()=>move(1)} aria-label="Move entry down"><ArrowDown size={16}/></button><button className="icon-button" aria-label="Remove entry" onClick={()=>{if(confirm('Remove this entry? This takes effect when you save.')){change({...data,[section]:list.filter((_,i)=>i!==index)});setIndex(Math.max(0,index-1))}}}><Trash2 size={16}/></button></>}</div>{section==='events'&&<p className="studio-media-note">Add photos, videos and certificate images to this event. Upload each file, edit the descriptions below, and save. Categories: Award, Finalist, Participation, Community, or Research. New events start as drafts. Published events appear in Achievements and Hacke Diaries.</p>}{(section==='projects'||section==='events')&&<label className="studio-upload"><Upload size={17}/> {section==='events'?'Upload event photo or video':'Upload project image'}<input type="file" accept={section==='events'?'image/png,image/jpeg,image/webp,video/mp4,video/webm':'image/png,image/jpeg,image/webp'} disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value=''}}/></label>}<Field name={section} value={current} onChange={value=>change({...data,[section]:array?list.map((x,i)=>i===index?value:x):value})}/></>:<div className="empty-state"><h2>Start a new entry.</h2><p>New projects and notes begin as drafts.</p><button className="pill-button" onClick={add}><Plus size={16}/> Create entry</button></div>}</section></div></div>}



